import type { InstallSupplementCatalogItem } from "@/types/install-supplement";

export const INSTALL_SUPPLEMENT_CATALOG: InstallSupplementCatalogItem[] = [
  // Roofing
  {
    code: "RFG_ADDL_LAYER",
    description: "Additional layer removal (per SQ)",
    category: "ROOFING",
    default_unit: "SQ",
    default_unit_price: 75.0,
    typical_reason: "Multiple layers found during tear-off",
    building_code: "IRC R907.3 — max 2 layers; 3+ requires full tear-off to deck",
  },
  {
    code: "RFG_PLY",
    description: "Plywood/OSB decking replacement",
    category: "ROOFING",
    default_unit: "SF",
    default_unit_price: 3.25,
    typical_reason: "Rotten or under-code decking discovered during tear-off",
    building_code: "IRC R803.2.1 — min 7/16\" OSB or 15/32\" plywood for roof sheathing",
  },
  {
    code: "RFG_FASCIA",
    description: "Rotten fascia board replacement",
    category: "ROOFING",
    default_unit: "LF",
    default_unit_price: 8.50,
    typical_reason: "Hidden rot discovered behind gutters during installation",
    building_code: null,
  },
  {
    code: "RFG_DRIP",
    description: "Drip edge installation (code upgrade)",
    category: "ROOFING",
    default_unit: "LF",
    default_unit_price: 4.75,
    typical_reason: "Missing or damaged drip edge found during tear-off",
    building_code: "IRC R905.2.8.5 — drip edge required at eaves and gables",
  },
  {
    code: "RFG_DECK_REPAIR",
    description: "Decking spot repair (water damage)",
    category: "ROOFING",
    default_unit: "SF",
    default_unit_price: 4.50,
    typical_reason: "Localized water damage to decking visible after shingle removal",
    building_code: null,
  },
  {
    code: "RFG_RIDGE_BOARD",
    description: "Ridge board replacement",
    category: "ROOFING",
    default_unit: "LF",
    default_unit_price: 12.00,
    typical_reason: "Cracked or deteriorated ridge board found during cap removal",
    building_code: null,
  },
  {
    code: "RFG_PIPE_BOOT",
    description: "Pipe boot / vent flashing replacement",
    category: "ROOFING",
    default_unit: "EA",
    default_unit_price: 85.00,
    typical_reason: "Cracked or deteriorated pipe boots found during installation",
    building_code: null,
  },
  {
    code: "RFG_CHIMNEY_FLASH",
    description: "Chimney flashing replacement (step + counter)",
    category: "ROOFING",
    default_unit: "EA",
    default_unit_price: 450.00,
    typical_reason: "Chimney flashing in worse condition than visible from ground",
    building_code: "IRC R903.2.1 — flashing at wall/roof intersections",
  },
  // Siding
  {
    code: "SDG_HOUSEWRAP",
    description: "House wrap / WRB installation",
    category: "SIDING",
    default_unit: "SF",
    default_unit_price: 1.25,
    typical_reason: "Missing weather-resistant barrier discovered behind siding",
    building_code: "IRC R703.1 — WRB required behind exterior cladding",
  },
  {
    code: "SDG_INSULATION",
    description: "Insulation board replacement",
    category: "SIDING",
    default_unit: "SF",
    default_unit_price: 2.50,
    typical_reason: "Damaged or under-code insulation board behind siding",
    building_code: null,
  },
  {
    code: "SDG_SHEATHING",
    description: "Wall sheathing repair",
    category: "SIDING",
    default_unit: "SF",
    default_unit_price: 3.75,
    typical_reason: "Water-damaged wall sheathing found behind removed siding",
    building_code: null,
  },
  // General
  {
    code: "GEN_DUMPSTER",
    description: "Additional dumpster load",
    category: "GENERAL",
    default_unit: "EA",
    default_unit_price: 450.00,
    typical_reason: "Excess debris from multiple layers or hidden damage",
    building_code: null,
  },
  {
    code: "GEN_MOLD",
    description: "Mold remediation (surface treatment)",
    category: "GENERAL",
    default_unit: "SF",
    default_unit_price: 6.00,
    typical_reason: "Mold growth found under damaged roofing/siding materials",
    building_code: null,
  },
  {
    code: "GEN_WATER_DMG",
    description: "Water damage remediation",
    category: "GENERAL",
    default_unit: "SF",
    default_unit_price: 5.50,
    typical_reason: "Hidden water damage behind materials",
    building_code: null,
  },
];

export const CATALOG_CATEGORIES = [...new Set(INSTALL_SUPPLEMENT_CATALOG.map((i) => i.category))];
