import { PDFDocument, StandardFonts, rgb, type PDFFont } from "pdf-lib";

/**
 * Retail estimate PDF generator — pure JS via pdf-lib, no chromium.
 *
 * Strict isolation from the claims pipeline (per Tom's directive after
 * the 2026-05-21 puppeteer disaster + "retail and insurance two completely
 * different work flows, dont want any mixing of the two"). Claims PDFs are
 * generated by Python/Chrome headless on Railway via usarm_pdf_generator.py.
 * This module ONLY generates retail estimate proposals and lives on the
 * Next.js side. Zero shared code with claims PDF gen.
 *
 * Returns a Uint8Array ready to attach to a Resend email (base64-encode at
 * the call site) or stream to the browser.
 */

interface RetailPdfInput {
  customerName: string | null | undefined;
  customerAddress: string | null | undefined;
  customerEmail: string | null | undefined;
  companyName: string;
  companyPhone: string | null | undefined;
  companyEmail: string | null | undefined;
  companyAddress: string | null | undefined;
  companyLicense: string | null | undefined;
  productName: string;
  manufacturer: string;
  manufacturerSeries: string | null | undefined;
  warrantyDisclosure: string | null | undefined;
  totalAmount: number;
  baseAmount: number;
  addonsAmount: number;
  subtotalAmount: number;
  markupPct: number;
  markupAmount: number;
  measurementsSummary: Array<{ label: string; value: number; unit: string }>;
  addonLineItems: Array<{ description: string; qty: number; lineTotal: number }>;
  estimateDate: Date;
  paymentLinkUrl?: string | null;
  signLinkUrl?: string | null;
}

const MARGIN = 50;
const PAGE_W = 612; // US Letter portrait
const PAGE_H = 792;
const COLOR_TEXT = rgb(0.1, 0.1, 0.13);
const COLOR_MUTED = rgb(0.45, 0.45, 0.5);
const COLOR_ACCENT = rgb(0.91, 0.23, 0.42); // pink-ish brand tint
const COLOR_DIVIDER = rgb(0.85, 0.85, 0.88);
const COLOR_TABLE_HEADER_BG = rgb(0.97, 0.97, 0.98);

function usd(n: number): string {
  return n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });
}

function fmtDate(d: Date): string {
  return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

/** Soft text wrap: returns an array of lines that fit within maxWidth. */
function wrap(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = (text || "").split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const w of words) {
    const trial = current ? `${current} ${w}` : w;
    const width = font.widthOfTextAtSize(trial, size);
    if (width > maxWidth && current) {
      lines.push(current);
      current = w;
    } else {
      current = trial;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export async function generateRetailEstimatePdf(input: RetailPdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(`Retail Estimate — ${input.customerName || input.customerAddress || "Estimate"}`);
  doc.setProducer("DumbRoof / pdf-lib");
  doc.setCreator(input.companyName);

  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;

  const drawText = (
    text: string,
    x: number,
    yPos: number,
    opts: { size?: number; bold?: boolean; color?: ReturnType<typeof rgb>; maxW?: number } = {},
  ): number => {
    const size = opts.size ?? 10;
    const f = opts.bold ? fontBold : font;
    const color = opts.color ?? COLOR_TEXT;
    if (opts.maxW) {
      const lines = wrap(text, f, size, opts.maxW);
      let cursor = yPos;
      for (const line of lines) {
        page.drawText(line, { x, y: cursor, size, font: f, color });
        cursor -= size * 1.35;
      }
      return cursor;
    }
    page.drawText(text, { x, y: yPos, size, font: f, color });
    return yPos - size * 1.35;
  };

  const drawDivider = (yPos: number, color = COLOR_DIVIDER) => {
    page.drawLine({
      start: { x: MARGIN, y: yPos },
      end: { x: PAGE_W - MARGIN, y: yPos },
      thickness: 0.7,
      color,
    });
  };

  // Ensure we have room on the page; add a new page if not.
  const ensureRoom = (neededHeight: number) => {
    if (y - neededHeight < MARGIN + 30) {
      page = doc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - MARGIN;
    }
  };

  // ─── Header: company info (left) + ESTIMATE label + date (right) ─────
  drawText(input.companyName, MARGIN, y, { size: 18, bold: true });
  page.drawText("RETAIL ESTIMATE", {
    x: PAGE_W - MARGIN - fontBold.widthOfTextAtSize("RETAIL ESTIMATE", 11),
    y,
    size: 11,
    font: fontBold,
    color: COLOR_ACCENT,
  });
  y -= 22;

  const headerLines: string[] = [];
  if (input.companyAddress) headerLines.push(input.companyAddress);
  if (input.companyPhone || input.companyEmail) {
    headerLines.push(
      [input.companyPhone, input.companyEmail].filter(Boolean).join(" · "),
    );
  }
  if (input.companyLicense) headerLines.push(`License: ${input.companyLicense}`);
  for (const line of headerLines) {
    page.drawText(line, { x: MARGIN, y, size: 9, font, color: COLOR_MUTED });
    y -= 12;
  }
  page.drawText(`Issued ${fmtDate(input.estimateDate)}`, {
    x: PAGE_W - MARGIN - font.widthOfTextAtSize(`Issued ${fmtDate(input.estimateDate)}`, 9),
    y: y + 12,
    size: 9,
    font,
    color: COLOR_MUTED,
  });
  y -= 10;
  drawDivider(y);
  y -= 18;

  // ─── Customer + Property ─────────────────────────────────────────────
  drawText("PREPARED FOR", MARGIN, y, { size: 8, bold: true, color: COLOR_MUTED });
  y -= 13;
  if (input.customerName) y = drawText(input.customerName, MARGIN, y, { size: 11, bold: true });
  if (input.customerAddress)
    y = drawText(input.customerAddress, MARGIN, y, { size: 10, color: COLOR_MUTED, maxW: PAGE_W - 2 * MARGIN });
  if (input.customerEmail) y = drawText(input.customerEmail, MARGIN, y, { size: 9, color: COLOR_MUTED });
  y -= 12;
  drawDivider(y);
  y -= 18;

  // ─── Product ─────────────────────────────────────────────────────────
  drawText("PRODUCT", MARGIN, y, { size: 8, bold: true, color: COLOR_MUTED });
  y -= 13;
  y = drawText(input.productName, MARGIN, y, { size: 13, bold: true });
  const productLine = [input.manufacturer, input.manufacturerSeries].filter(Boolean).join(" · ");
  if (productLine) y = drawText(productLine, MARGIN, y, { size: 10, color: COLOR_MUTED });
  y -= 14;

  // ─── Measurements summary (compact 2-column) ─────────────────────────
  const measRows = (input.measurementsSummary || []).filter((m) => m.value > 0);
  if (measRows.length) {
    ensureRoom(40 + measRows.length * 14);
    drawText("MEASUREMENTS", MARGIN, y, { size: 8, bold: true, color: COLOR_MUTED });
    y -= 13;
    const colW = (PAGE_W - 2 * MARGIN) / 2;
    const half = Math.ceil(measRows.length / 2);
    const left = measRows.slice(0, half);
    const right = measRows.slice(half);
    let rowY = y;
    const rowsCount = Math.max(left.length, right.length);
    for (let i = 0; i < rowsCount; i++) {
      if (left[i]) {
        page.drawText(left[i].label, { x: MARGIN, y: rowY, size: 9, font, color: COLOR_MUTED });
        const valStr = `${left[i].value.toLocaleString()} ${left[i].unit}`;
        page.drawText(valStr, {
          x: MARGIN + colW - 10 - font.widthOfTextAtSize(valStr, 9),
          y: rowY,
          size: 9,
          font: fontBold,
        });
      }
      if (right[i]) {
        page.drawText(right[i].label, { x: MARGIN + colW, y: rowY, size: 9, font, color: COLOR_MUTED });
        const valStr = `${right[i].value.toLocaleString()} ${right[i].unit}`;
        page.drawText(valStr, {
          x: PAGE_W - MARGIN - font.widthOfTextAtSize(valStr, 9),
          y: rowY,
          size: 9,
          font: fontBold,
        });
      }
      rowY -= 14;
    }
    y = rowY - 4;
    drawDivider(y);
    y -= 18;
  }

  // ─── Pricing table ───────────────────────────────────────────────────
  ensureRoom(60 + (input.addonLineItems?.length || 0) * 16);
  drawText("PRICING", MARGIN, y, { size: 8, bold: true, color: COLOR_MUTED });
  y -= 13;

  const totalCol = PAGE_W - MARGIN;
  // Table header band
  page.drawRectangle({
    x: MARGIN,
    y: y - 4,
    width: PAGE_W - 2 * MARGIN,
    height: 20,
    color: COLOR_TABLE_HEADER_BG,
  });
  page.drawText("Item", { x: MARGIN + 8, y: y + 4, size: 9, font: fontBold, color: COLOR_MUTED });
  page.drawText("Amount", {
    x: totalCol - fontBold.widthOfTextAtSize("Amount", 9) - 8,
    y: y + 4,
    size: 9,
    font: fontBold,
    color: COLOR_MUTED,
  });
  y -= 22;

  // Base line
  page.drawText(`${input.productName} — all-in`, { x: MARGIN + 8, y, size: 10, font });
  const baseStr = usd(input.baseAmount);
  page.drawText(baseStr, {
    x: totalCol - font.widthOfTextAtSize(baseStr, 10) - 8,
    y,
    size: 10,
    font: fontBold,
  });
  y -= 16;

  for (const ad of input.addonLineItems || []) {
    const label = `${ad.description} × ${ad.qty}`;
    const trimmed = label.length > 65 ? `${label.slice(0, 62)}…` : label;
    page.drawText(trimmed, { x: MARGIN + 8, y, size: 10, font });
    const amt = usd(ad.lineTotal);
    page.drawText(amt, {
      x: totalCol - font.widthOfTextAtSize(amt, 10) - 8,
      y,
      size: 10,
      font: fontBold,
    });
    y -= 15;
  }

  if (input.markupPct !== 0) {
    y -= 6;
    drawDivider(y + 6);
    page.drawText("Subtotal", { x: MARGIN + 8, y, size: 10, font, color: COLOR_MUTED });
    const sub = usd(input.subtotalAmount);
    page.drawText(sub, {
      x: totalCol - font.widthOfTextAtSize(sub, 10) - 8,
      y,
      size: 10,
      font,
      color: COLOR_MUTED,
    });
    y -= 14;
    const markupLabel = input.markupPct > 0 ? `Markup (+${input.markupPct}%)` : `Discount (${input.markupPct}%)`;
    page.drawText(markupLabel, { x: MARGIN + 8, y, size: 10, font, color: COLOR_MUTED });
    const mp = `${input.markupAmount >= 0 ? "+" : ""}${usd(input.markupAmount)}`;
    page.drawText(mp, {
      x: totalCol - font.widthOfTextAtSize(mp, 10) - 8,
      y,
      size: 10,
      font,
      color: COLOR_MUTED,
    });
    y -= 16;
  }

  // Grand total band
  y -= 4;
  page.drawRectangle({
    x: MARGIN,
    y: y - 6,
    width: PAGE_W - 2 * MARGIN,
    height: 30,
    color: rgb(0.04, 0.04, 0.1),
  });
  page.drawText("TOTAL", {
    x: MARGIN + 12,
    y: y + 4,
    size: 13,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  const totalStr = usd(input.totalAmount);
  page.drawText(totalStr, {
    x: totalCol - fontBold.widthOfTextAtSize(totalStr, 17) - 12,
    y: y + 1,
    size: 17,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  y -= 36;

  // ─── Sign / Pay CTAs (if URLs provided) ───────────────────────────
  if (input.signLinkUrl || input.paymentLinkUrl) {
    ensureRoom(40);
    if (input.signLinkUrl) {
      page.drawText("Accept and sign online:", { x: MARGIN, y, size: 9, font, color: COLOR_MUTED });
      y -= 12;
      page.drawText(input.signLinkUrl, { x: MARGIN, y, size: 9, font: fontBold, color: COLOR_ACCENT });
      y -= 18;
    }
    if (input.paymentLinkUrl) {
      page.drawText("Pay your deposit:", { x: MARGIN, y, size: 9, font, color: COLOR_MUTED });
      y -= 12;
      page.drawText(input.paymentLinkUrl, { x: MARGIN, y, size: 9, font: fontBold, color: COLOR_ACCENT });
      y -= 18;
    }
  }

  // ─── Warranty disclosure (if present) ───────────────────────────────
  if (input.warrantyDisclosure) {
    ensureRoom(60);
    drawDivider(y);
    y -= 16;
    drawText("WARRANTY", MARGIN, y, { size: 8, bold: true, color: COLOR_MUTED });
    y -= 13;
    y = drawText(input.warrantyDisclosure, MARGIN, y, {
      size: 9,
      color: COLOR_MUTED,
      maxW: PAGE_W - 2 * MARGIN,
    });
    y -= 8;
  }

  // ─── Footer ──────────────────────────────────────────────────────────
  ensureRoom(40);
  drawDivider(y);
  y -= 12;
  drawText(
    `Prepared by ${input.companyName}. This estimate is valid for 30 days from issuance. Final price may adjust based on conditions discovered during tear-off or installation.`,
    MARGIN,
    y,
    { size: 8, color: COLOR_MUTED, maxW: PAGE_W - 2 * MARGIN },
  );

  return doc.save();
}
