import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { sendCAPIEvent } from "@/lib/meta-capi";

// POST /api/onboarding/upload
//
// Authed staging upload for the Richard onboarding agent (/welcome). A brand-new,
// signed-in user drops photos / a carrier scope / a measurement report into the
// chat upload box; this stores each file under the canonical claim layout
// `{user_id}/{slug}/{folder}/{name}` BEFORE the claim row exists. Richard's
// `create_claim_from_minimal_input` tool later DISCOVERS these by listing the
// slug prefix and inserts the claim — no file moves needed.
//
// Mirrors the proven anonymous `instant-intake/upload` pattern, but authed and
// slug-scoped (the slug is generated by the /welcome UI per onboarding session).

const BUCKET = "claim-documents";
const VALID_FOLDERS = new Set(["photos", "measurements", "scope"]);
const MAX_BYTES = 50 * 1024 * 1024; // 50MB/file — phone photos can be large

function sanitizeFileName(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "_").replace(/_{2,}/g, "_").slice(0, 120);
}

export async function POST(request: Request) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
    }

    const formData = await request.formData();
    const file = formData.get("file");
    const folder = formData.get("folder");
    const slug = formData.get("slug");

    if (!(file instanceof File)) {
      return NextResponse.json({ error: "Missing file" }, { status: 400 });
    }
    if (typeof folder !== "string" || !VALID_FOLDERS.has(folder)) {
      return NextResponse.json({ error: "Invalid folder" }, { status: 400 });
    }
    // Slug is the onboarding-session id from the UI. Strict format so the upload
    // path can never escape the caller's own `{user_id}/` prefix.
    if (typeof slug !== "string" || !/^[A-Za-z0-9_-]{4,64}$/.test(slug)) {
      return NextResponse.json({ error: "Invalid session id" }, { status: 400 });
    }
    if (file.size <= 0) {
      // A 0-byte file becomes empty base64 and fails the Vision call — reject at the
      // door so it never reaches a claim (the first-claim-must-not-fail rule).
      return NextResponse.json({ error: "That file looks empty — please re-pick it" }, { status: 400 });
    }
    if (file.size > MAX_BYTES) {
      return NextResponse.json({ error: "File exceeds 50MB" }, { status: 413 });
    }

    const safeName = sanitizeFileName(file.name || `${folder}-${Date.now()}`);
    const path = `${user.id}/${slug}/${folder}/${safeName}`;
    const bytes = new Uint8Array(await file.arrayBuffer());

    const { error: storageError } = await supabaseAdmin.storage
      .from(BUCKET)
      .upload(path, bytes, {
        contentType: file.type || "application/octet-stream",
        upsert: true,
      });
    if (storageError) {
      return NextResponse.json({ error: storageError.message }, { status: 500 });
    }

    // Server-side Meta CAPI Upload event (iOS/adblock-resilient). Non-blocking —
    // the upload already succeeded; attribution is best-effort.
    const ua = request.headers.get("user-agent") || undefined;
    const ip =
      request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
      request.headers.get("x-real-ip") ||
      undefined;
    sendCAPIEvent({
      eventName: "Upload",
      eventSourceUrl: request.headers.get("referer") || undefined,
      userData: { clientUserAgent: ua, clientIpAddress: ip },
      customData: { funnel: "richard_onboarding", folder, filename: safeName },
    }).catch(() => {});

    return NextResponse.json({ ok: true, slug, folder, filename: safeName });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Upload failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
